["Natural constants"]
mu=3.986004418e14
g0= 9.80665
"Rad Earth"=6371800
"Pos sun"=[151023e7,0e1,0e1]
u_sun=[1,0,0]
a_earth=6378.1e3
b_earth=6356.7e3

["Satellite parameters"]
"dry mass"=54.0
"fuel mass"=2.8
Cd=2.2 #2.027
"A_extended"= 0.19547
"A_solar"=1.38
Thrust=5e-3
I_sp=3000
"SP side area"=0.0016
"Third moving panel" = 0
"Third panel area"=0.221
"Min drag"= 1 #true=1 or false=0
"SP pointing accuracy"=0.087 #In radians

["Orbital parameters"]
"Starting alt"=230e3
"Min alt"=295e3
"Max alt"=305e3
e=0
a=6671.8e3
i=1.6755
omega_AP=0
omega_LAN=0
T=0
EA=0
t=0


